# Use postgres/example user/password credentials
version: '3.9'

services:
  web: 
      image: tbs1Lads/zahlenraten
      ports:
      - "8000:5000"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=zahlenraten
      - POSTGRES_PASSWORD=CYrcTzCEKyDtq&N0M
      - POSTGRES_DB=game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  backend:

volumes:
  pgdata:
